In [52]:
import numpy as np
import pandas as pd
import os


In [53]:
# funcion que devuelve los indices donde un array es distinto a otro
#recorre los dos arrays y compara si son iguales, si no lo son guarda el indice
def diff(first, second):
        listaa=[]
        for i in range(len(second)):

            if first[i] != second[i]:
                listaa.append(i)

                break
        return listaa

In [65]:
metadata_train= pd.read_csv('data/Limpio/PreProcesado/train.csv')

In [66]:
metadata_test= pd.read_csv('data/Limpio/PreProcesado/test.csv')

In [67]:
from src.ingenieria_datos import OneHot

onehot_test = OneHot.feature_engineering(metadata_test,train=True)
onehot_train = OneHot.feature_engineering(metadata_train,train=True)

np.save('metadata_test.npy', onehot_test)
np.save('metadata_train.npy', onehot_train)


(22342, 20)
(22342, 370)


Completando filas: 0it [00:00, ?it/s]/Users/jackspolski/Documents/UDESA/machine learning/Car_prediction/src/ingenieria_datos/OneHot.py:74: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_final = pd.concat([df_final, new_row], ignore_index = True)
Completando filas: 2238it [00:06, 352.26it/s]


(22342, 20)
(22342, 370)


Completando filas: 0it [00:00, ?it/s]/Users/jackspolski/Documents/UDESA/machine learning/Car_prediction/src/ingenieria_datos/OneHot.py:74: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_final = pd.concat([df_final, new_row], ignore_index = True)
Completando filas: 20139it [05:51, 57.24it/s]


In [56]:
onehot_train = OneHot.feature_engineering(metadata_train2,train=True)

(22342, 20)
(22342, 370)


Completando filas: 0it [00:00, ?it/s]/Users/jackspolski/Documents/UDESA/machine learning/Car_prediction/src/ingenieria_datos/OneHot.py:74: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_final = pd.concat([df_final, new_row], ignore_index = True)
Completando filas: 20139it [05:52, 57.19it/s]


In [21]:
print(onehot.shape)
print(metadata_test.shape)



(2238, 370)
(2238, 372)


In [57]:
diferencias=[]
for i in range(metadata_train.shape[0]):
    diferencias.append(diff(metadata_train[i],onehot_train[i]))

print(diferencias)
    

[[351], [351], [351], [351], [351], [351], [351], [353], [352], [353], [353], [353], [352], [353], [351], [353], [351], [351], [351], [352], [353], [351], [351], [351], [351], [351], [351], [353], [351], [352], [351], [351], [351], [352], [351], [351], [353], [353], [351], [352], [351], [353], [351], [352], [351], [353], [352], [352], [351], [351], [353], [351], [351], [353], [351], [351], [352], [351], [351], [351], [353], [351], [351], [351], [353], [351], [351], [351], [352], [351], [352], [352], [351], [351], [351], [351], [351], [352], [351], [353], [352], [351], [351], [351], [351], [351], [351], [351], [353], [351], [351], [351], [351], [351], [352], [351], [352], [351], [351], [353], [351], [351], [351], [352], [352], [351], [351], [353], [351], [351], [351], [351], [351], [351], [351], [351], [351], [351], [353], [351], [351], [352], [351], [352], [352], [352], [351], [352], [351], [351], [351], [351], [351], [352], [351], [351], [351], [351], [351], [352], [351], [351], [353]

In [58]:
print(np.unique(diferencias))

[351 352 353]


In [59]:
#agregar en onehot una columna de 0s en la anterior a la 351 
#entre 350 y 351
onehot = np.insert(onehot, 350, 0, axis=1)


In [46]:
print(onehot.shape)

(2238, 371)


In [62]:
#agregar en onehot una columna de 0s en la anterior a la 352
#entre 351 y 352
onehot = np.insert(onehot, 351, 0, axis=1)
print(onehot.shape)


(2238, 374)


In [63]:
diferencias=[]
for i in range(metadata_train.shape[0]):
    diferencias.append(diff(metadata_train[i],onehot_train[i]))

print(diferencias)

print(np.unique(diferencias))

[[351], [351], [351], [351], [351], [351], [351], [353], [352], [353], [353], [353], [352], [353], [351], [353], [351], [351], [351], [352], [353], [351], [351], [351], [351], [351], [351], [353], [351], [352], [351], [351], [351], [352], [351], [351], [353], [353], [351], [352], [351], [353], [351], [352], [351], [353], [352], [352], [351], [351], [353], [351], [351], [353], [351], [351], [352], [351], [351], [351], [353], [351], [351], [351], [353], [351], [351], [351], [352], [351], [352], [352], [351], [351], [351], [351], [351], [352], [351], [353], [352], [351], [351], [351], [351], [351], [351], [351], [353], [351], [351], [351], [351], [351], [352], [351], [352], [351], [351], [353], [351], [351], [351], [352], [352], [351], [351], [353], [351], [351], [351], [351], [351], [351], [351], [351], [351], [351], [353], [351], [351], [352], [351], [352], [352], [352], [351], [352], [351], [351], [351], [351], [351], [352], [351], [351], [351], [351], [351], [352], [351], [351], [353]

In [30]:
#fijarse en las columnas -19 hasta -23 en cual aparece almenos un 1
list=[]

for i in range(0,metadata_test.shape[0]):
    #fijarse en los elementos -19 hasta -23 en cual aparece almenos un 1
    if metadata_test[i][353]==1:
        list.append(19)
    if metadata_test[i][352]==1:
        list.append(20)
    if metadata_test[i][351]==1:
        list.append(21)
    if metadata_test[i][350]==1:
        list.append(22)
    if metadata_test[i][349]==1:
        list.append(23)

In [31]:
print(np.unique(list))

[19 20 23]


In [32]:
#fijarse en las columnas -19 hasta -23 en cual aparece almenos un 1
list=[]

for i in range(0,metadata_train.shape[0]):
    #fijarse en los elementos -19 hasta -23 en cual aparece almenos un 1
    if metadata_train[i][353]==1:
        list.append(19)
    if metadata_train[i][352]==1:
        list.append(20)
    if metadata_train[i][351]==1:
        list.append(21)
    if metadata_train[i][350]==1:
        list.append(22)
    if metadata_train[i][349]==1:
        list.append(23)

        

In [33]:
#dame los valores unicos de la lista

print(np.unique(list))


[19 20 22 23]


In [ ]:
#agregar una columna de 0 en la 351


In [2]:
test_preproesado = pd.read_csv('test_entrega/test_procesado.csv')


In [7]:
test_preproesado.head()

Marca Modelo     Año   Versión     Color Tipo de combustible  Puertas  \
0  PEUGEOT   2008  2018.0    ALLURE     NEGRO               NAFTA      5.0   
1  PEUGEOT   2008  2024.0    FELINE    BLANCO               NAFTA      5.0   
2  PEUGEOT   2008  2019.0  CROSSWAY      GRIS               NAFTA      5.0   
3  PEUGEOT   2008  2017.0     SPORT  PLATEADO               NAFTA      5.0   
4  PEUGEOT   2008  2016.0     SPORT      ROJO               NAFTA      5.0   

  Transmisión Motor Tipo de carrocería  Kilómetros  \
0  AUTOMÁTICA   1.6                SUV    106650.0   
1      MANUAL   1.6                SUV     20000.0   
2      MANUAL   1.6                SUV     36080.0   
3      MANUAL   1.6                SUV     78000.0   
4      MANUAL   1.6                SUV     73000.0   

                        Título  Precio Moneda Tipo de vendedor  \
0  Peugeot 2008 1.6 Allure Tip       0    USD           TIENDA   
1      Peugeot 2008 1.6 Feline       0    USD           TIENDA   
2    Peugeot 2008 1.6 Crossway       0    USD           TIENDA   
3   Peugeot 2008 1.6 Thp Sport       0    USD           TIENDA   
4   Peugeot 2008 1.6 Thp Sport       0    USD    CONCESIONARIA   

  Con cámara de retroceso  Cilindrada Tracción Turbo 7plazas  
0               NO INDICA         1.6     OTRO    NO      NO  
1               NO INDICA         1.6     OTRO    NO      NO  
2               NO INDICA         1.6     OTRO    NO      NO  
3                      SÍ         1.6     OTRO    SI      NO  
4               NO INDICA         1.6     OTRO    SI      NO

In [3]:
from src.ingenieria_datos import OneHot


In [4]:
test_onehot = OneHot.feature_engineering(test_preproesado,train=True)

Completando filas: 0it [00:00, ?it/s]/Users/jackspolski/Documents/UDESA/machine learning/Car_prediction/src/ingenieria_datos/OneHot.py:74: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_final = pd.concat([df_final, new_row], ignore_index = True)
Completando filas: 8551it [01:05, 130.13it/s]


In [12]:
# guardar en npy
np.save('test_entrega/test_onehot.npy', test_onehot)


In [18]:
# descargar metadata_test de results.onehot './results/OneHot/metadata_test.npy'

metadata_test = np.load('results/OneHot/metadata_test.npy', allow_pickle=True)


In [21]:
print(metadata_test[0])

[2021.0 42000.0 1.6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0
 0 0 0 1 0 0 1 0 19417.4757]


In [6]:
print(test_onehot[0])

[2018.0 106650.0 1.6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0
 0 1 0 0 1 0 0]


# Pasar por NN

In [8]:
# importar nn que hace el encoding que esta en src/ingenieria_datos/NN.pth
# esa red ya esta entrenada y se puede usar para hacer el encoding de los datos 
# la arquitectura de la red esta en src/ingenieria_datos/NN.py
import torch
import torch.nn as nn
import torch.nn.functional as F
from src.ingenieria_datos import NN
model=NN.SimpleNN()
model.load_state_dict(torch.load('src/ingenieria_datos/NN.pth'))
model.eval()





TypeError: SimpleNN.__init__() missing 1 required positional argument: 'input_dim'